name: deploy

on:
  # Trigger the deploy on push to master branch
  push:
    branches:
      - master

jobs: 
  # This job deploys the example book
  deploy-example-book:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.8]
    steps:
    - uses: actions/checkout@v2
    # Install CC
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install cookiecutter
    # Use default CC
    - name: Cookiecutter no GHA
      run: |
        cookiecutter . --no-input include_github_actions=no
    # Install requirements.txt
    - name: Install requirements
      run: |
        pip install -r my_book/requirements.txt
    # Build the example book
    - name: Build book
      run: |
        jupyter-book build my_book/my_book/
    # Deploy html to gh-pages
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: my_book/my_book/_build/html
